name: Generate Keystore
on: workflow_dispatch
jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkey -v \
            -keystore kairos.keystore \
            -alias kairos \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass kairos123 -keypass kairos123 \
            -dname "CN=Kairos, O=App, C=US"
          base64 -w 0 kairos.keystore > kairos.keystore.base64.txt
          cat kairos.keystore.base64.txt

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: kairos-keystore
          path: kairos.keystore.base64.txt
